version: "3.7"

x-logging: &fluent-bit
  driver: "fluentd"
  options:
    fluentd-address: 172.19.0.8:24224

services:

  gateway:
    build: 
      context: ./gateway
      dockerfile: Dockerfile
    image: gateway
    container_name: gateway_service
    restart: always
    networks:
      - servers
      - monitoring
    ports:
      - 8070:8070
      - 8071:8071
    logging: *fluent-bit
    depends_on:
      - stakeholders
      - shopping

  nats-server:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"
    command: "-js"
    networks: 
      - servers
      - monitoring
    logging: *fluent-bit

  stakeholders:
    build:
      context: .
      dockerfile: Stakeholders/Dockerfile
    image: stakeholders
    container_name: stakeholders_service
    environment:
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      NATS_HOST: nats-server
      NATS_PORT: 4222
      NATS_USER: ""
      NATS_PASS: ""
      PURCHASE_COMMAND_SUBJECT: purchase.checkout.command
      PURCHASE_REPLY_SUBJECT: purchase.checkout.reply
      NATS_QUEUE_GROUP: stakeholders_service
    restart: always
    networks:
      - servers
      - monitoring
    logging: *fluent-bit
    ports:
      - 8080:8080
      - 50051:50051 
    depends_on:
      - database
      - nats-server

  database:
    image: postgres
    container_name: stakeholders_postgres
    restart: always
    networks:
      - servers
      - monitoring
    logging: *fluent-bit
    ports:
      - 5000:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super
      POSTGRES_DB: stakeholders
    volumes:
      - postgres-data:/var/lib/postgresql/data

  blog:
    build:
      context: ./blog
      dockerfile: Dockerfile
    image: blog
    container_name: blog_service
    restart: always
    environment:
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    networks:
      - servers
      - monitoring
    logging: *fluent-bit
    ports:
      - 8081:8081
      - 50052:50052
    volumes:
      - ./blog-data/uploads:/uploads 
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo
    container_name: blog_mongo
    restart: always
    networks:
      - servers
      - monitoring
    logging: *fluent-bit
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db

  tours:
    build:
      context: ./tours
      dockerfile: Dockerfile
    container_name: tours_service
    ports:
      - "8084:8084"  
    depends_on:
     - tour_database
    networks:
      - servers
      - monitoring
    logging: *fluent-bit

  tour_database:
    image: postgres
    container_name: tour_postgres
    restart: always
    networks:
      - servers
      - monitoring
    logging: *fluent-bit
    ports:
      - 5001:5432
    environment:
      POSTGRES_USER: postgres_tour
      POSTGRES_PASSWORD: super_tour
      POSTGRES_DB: toursdb
    volumes:
      - postgres-data-tours:/var/lib/postgresql/data
      
  shopping:
    build:
      context: .
      dockerfile: Shopping/Dockerfile
    image: shopping
    container_name: shopping_service
    environment:
      - NATS_HOST=nats-server
      - NATS_PORT=4222
      - NATS_USER=
      - NATS_PASS=
      - PURCHASE_COMMAND_SUBJECT=purchase.checkout.command
      - PURCHASE_REPLY_SUBJECT=purchase.checkout.reply
      - NATS_QUEUE_GROUP=shopping_service
    restart: always
    networks:
      - servers
      - monitoring
    logging: *fluent-bit
    ports:
      - 8082:8082
    depends_on:
      - shopping_database
      - nats-server


  shopping_database:
    image: postgres
    container_name: shopping_postgres
    restart: always
    networks:
      - servers
      - monitoring
    logging: *fluent-bit
    ports:
      - 5002:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super
      POSTGRES_DB: shopping
    volumes:
      - postgres-data-shopping:/var/lib/postgresql/data

  followers:
    build:
      context: ./followers
      dockerfile: Dockerfile
    image: followers
    container_name: followers_service
    restart: always
    networks:
      - servers
      - monitoring
    ports:
      - 8083:8083
    depends_on:
      - neo4j


  neo4j:
    image: neo4j:5.20
    container_name: follower_neo4j
    restart: always
    networks:
      - servers
      - monitoring
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password123
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins

volumes:
  postgres-data:
  postgres-data-tours:
  mongo-data:
  postgres-data-shopping:
  blog-data:

networks:
  servers:
    driver: bridge
  monitoring:
    external: true
